//gsap type definition
// interface gsap {
//   set(targets: any, vars: any): void;
//   to(targets: any, vars: any): void;
//   from(targets: any, vars: any): void;
//   fromTo(targets: any, vars: any, vars2: any): void;
//   allFrom(targets: any, vars: any): void;
//   allTo(targets: any, vars: any): void;
//   allFromTo(targets: any, vars: any, vars2: any): void;
//   getProperty(target: any, property: any): any;
//   getTweensOf(target: any): any;
//   killTweensOf(target: any): void;
//   invalidate(target: any): void;
//   updateRoot(target: any): void;
//   smoothTo(targets: any, vars: any): void;
//   smoothFromTo(targets: any, vars: any, vars2: any): void;
//   time(vars: any): number;
//   reverse(targets: any): void;
//   pause(targets: any): void;
//   play(targets: any): void;
//   progress(targets: any, value: any): void;
//   totalProgress(targets: any): number;
//   eventCallback(type: any, callback: any): void;
//   eventCallbackScope(type: any, callback: any, scope: any): void;
//   installPlugin(plugin: any): void;
//   registerEffect(effect: any): void;
//   registerEase(ease: any): void;
//   parseEase(ease: any): any;
//   parseColor(color: any): any;
//   parseUnit(unit: any): any;
//   parseNumber(number: any): any;
//   round(value: any, decimals: any): any;
//   snap(value: any, snap: any): any;
//   normalize(value: any, min: any, max: any): any;
//   map(value: any, min1: any, max1: any, min2: any, max2: any): any;
//   unmap(value: any, min1: any, max1: any, min2: any, max2: any): any;
//   linear(value: any, min: any, max: any): any;
//   pow(value: any, exp: any): any;
//   log(value: any, base: any): any;
//   sin(value: any): any;
//   cos(value: any): any;
//   tan(value: any): any;
//   asin(value: any): any;
//   acos(value: any): any;
//   atan(value: any): any;
//   atan2(value: any): any;
//   exp(value: any): any;
//   lerp(value: any, min: any, max: any): any;
//   backIn(value: any): any;
//   backOut(value: any): any;
//   backInOut(value: any): any;
//   elasticIn(value: any): any;
//   elasticOut(value: any): any;
//   elasticInOut(value: any): any;
//   bounceIn(value: any): any;
//   bounceOut(value: any): any;
//   bounceInOut(value: any): any;
//   fadeIn(value: any): any;
//   fadeOut(value: any): any;
//   fadeInOut(value: any): any;
//   crossFade(value: any): any;
//   slideIn(value: any): any;
//   slideOut(value: any): any;
//   slideInOut(value: any): any;
//   smoothStep(value: any): any;
//   slowMo(value: any): any;
//   quintIn(value: any): any;
//   quintOut(value: any): any;
//   quintInOut(value: any): any;
//   expoIn(value: any): any;
//   expoOut(value: any): any;
//   expoInOut(value: any): any;
//   circIn(value: any): any;
//   circOut(value: any): any;
//   circInOut(value: any): any;
//   backInOut(value: any): any;
//   backInOut(value: any): any;
//   sineIn(value: any): any;
//   sineOut(value: any): any;
//   sineInOut(value: any): any;
//   quadIn(value: any): any;
//   quadOut(value: any): any;
//   quadInOut(value: any): any;
//   cubicIn(value: any): any;
//   cubicOut(value: any): any;
//   cubicInOut(value: any): any;
//   quartIn(value: any): any;
//   quartOut(value: any): any;
//   quartInOut(value: any): any;
//   quintIn(value: any): any;
//   quintOut(value: any): any;
//   quintInOut(value: any): any;
//   quarIn(value: any): any;
//   quarOut(value: any): any;
//   quarInOut(value: any): any;
//   expoIn(value: any): any;
//   expoOut(value: any): any;
//   expoInOut(value: any): any;
//   circIn(value: any): any;
//   circOut(value: any): any;
//   circInOut(value: any): any;
//   elasticIn(value: any): any;
//   elasticOut(value: any): any;
//   elasticInOut(value: any): any;
//   backIn(value: any): any;
//   backOut(value: any): any;
//   backInOut(value: any): any;
//   bounceIn(value: any): any;
//   bounceOut(value: any): any;
//   bounceInOut(value: any): any;
//   fadeIn(value: any): any;
//   fadeOut(value: any): any;
//   fadeInOut(value: any): any;
//   crossFade(value: any): any;
//   slideIn(value: any): any;
//   slideOut(value: any): any;
//   slideInOut(value: any): any;
//   smoothStep(value: any): any;
//   slowMo(value: any): any;
//   linear(value: any): any;
//   sineIn(value: any): any;
//   sineOut(value: any): any;
//   sineInOut(value: any): any;
//   quadIn(value: any): any;
//   quadOut(value: any): any;
//   quadInOut(value: any): any;
//   cubicIn(value: any): any;
//   cubicOut(value: any): any;
//   cubicInOut(value: any): any;
//   quartIn(value: any): any;
//   quartOut(value: any): any;
//   quartInOut(value: any): any;
//   quintIn(value: any): any;
//   quintOut(value: any): any;
//   quintInOut(value: any): any;
//   quarIn(value: any): any;
//   quarOut(value: any): any;
//   quarInOut(value: any): any;
//   expoIn(value: any): any;
//   expoOut(value: any): any;
//   expoInOut(value: any): any;
//   circIn(value: any): any;
//   circOut(value: any): any;
//   circInOut(value: any): any;
//   elasticIn(value: any): any;
//   elasticOut(value: any): any;
//   elasticInOut(value: any): any;
//   backIn(value: any): any;
//   backOut(value: any): any;
//   backInOut(value: any): any;
//   bounceIn(value: any): any;
//   bounceOut(value: any): any;
//   bounceInOut(value: any): any;
//   fadeIn(value: any): any;
//   fadeOut(value: any): any;
//   fadeInOut(value: any): any;
//   crossFade(value: any): any;
//   slideIn(value: any): any;
//   slideOut(value: any): any;
//   slideInOut(value: any): any;
//   smoothStep(value: any): any;
//   slowMo(value: any): any;
// }
